#!/bin/bash

# Quick Start Guide for Running ML Benchmarks
# This script demonstrates the typical workflow

echo "=========================================="
echo "ML Benchmarks Quick Start Guide"
echo "=========================================="
echo ""

echo "1. LOCAL TESTING"
echo "   Run a quick test with few samples and steps:"
echo ""
echo "   python nos_ml_benchmarks.py \\"
echo "       --optimizer RS \\"
echo "       --benchmark linear_regression \\"
echo "       --seed 0 \\"
echo "       --n_optimizer_samples 5 \\"
echo "       --n_steps 100"
echo ""
echo "   This creates files in: ml_benchmark_results/linear_regression/"
echo ""

echo "2. SUBMIT SINGLE BENCHMARK WITH MULTIPLE SEEDS"
echo "   Run RS on linear regression with 10 seeds:"
echo ""
echo "   sbatch --array=0-9 run_ml_benchmark.sh RS linear_regression"
echo ""
echo "   Run RE on XOR MLP with 10 seeds:"
echo ""
echo "   sbatch --array=0-9 run_ml_benchmark.sh RE xor_mlp"
echo ""

echo "3. SUBMIT ALL COMBINATIONS"
echo "   Run all optimizer-benchmark combinations:"
echo ""
echo "   # First, edit submit_all_benchmarks.sh to set N_SEEDS"
echo "   # Then run:"
echo "   ./submit_all_benchmarks.sh"
echo ""
echo "   This submits: 2 optimizers × 4 benchmarks × N_SEEDS jobs"
echo ""

echo "4. MONITOR JOBS"
echo "   Check job status:"
echo ""
echo "   squeue -u \$USER"
echo ""
echo "   Check specific job output:"
echo ""
echo "   tail -f logs/ml_benchmark_JOBID_ARRAYID.out"
echo ""

echo "5. GENERATE PLOTS"
echo "   After jobs complete, create plots:"
echo ""
echo "   # Plot single benchmark"
echo "   python load_and_plot_results.py --benchmark linear_regression"
echo ""
echo "   # Plot all benchmarks"
echo "   ./plot_all_benchmarks.sh"
echo ""

echo "6. EXAMINE RESULTS"
echo "   View result files:"
echo ""
echo "   ls -lh ml_benchmark_results/linear_regression/"
echo ""
echo "   Examine specific result:"
echo ""
echo "   cat ml_benchmark_results/linear_regression/RS_0.json | jq ."
echo ""

echo "=========================================="
echo "IMPORTANT NOTES"
echo "=========================================="
echo ""
echo "• RS runs 4 optimizers (RS + Adam + AdamW + SGD)"
echo "• RE runs only 1 optimizer (RE)"
echo "• Each seed is independent (can run in parallel)"
echo "• Results are saved immediately (no waiting for all seeds)"
echo "• Incumbent history tracks best loss so far (for plotting)"
echo ""
echo "For more details, see README_UPDATED_STRUCTURE.md"
echo "=========================================="
